services:
  database:
    image: postgres:latest
    container_name: pg
    restart: always

    environment:
      POSTGRES_DB: ${DOCKER_DATABASE_USER}
      POSTGRES_USER: ${DOCKER_DATABASE_USER}
      POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASS}

    expose:
      - "${DOCKER_DATABASE_PORT}"
    volumes:
      - pg-data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"
    depends_on:
      - database

volumes:
  pg-data:
    driver: local